# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eecc24fddba27e1d26273c69c801496741939785c0977b874afc99943bad69ed57c3102af02ed8b5a56bbcd5f4f0185aa577f281728bfb1d0f9e0b5455ffca56

test:
  secret_key_base: 6ba8999acd07fc625ab412d87faa3f98ceb45f04ff706072bcefbdaf68856d4b7069eb3733fe9aebdef650ae71678d28b1fe925ff21aa7743e9eb09fb4a745a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
